### ISSUE TITLE
bug: Since 0.15.3 EZA_COLORS's size coloring tweaks stopped working

### ISSUE THREAD

**Issue by bew** [eza-community/eza#682]
You can see here I set the user color and the file size (for small files) using `EZA_COLORS` to the same red color.

In the first test, using eza 0.15.2 both the user and the file size are correctly red.
In the second test, using eza 0.15.3 the user is still red but the file size is the default green color.
![image](https://github.com/eza-community/eza/assets/9730330/2f1f6b59-030f-44ed-ab4b-25622b089d9f)

Working version, nixpkgs hash: `H=657f8ce31927e61a2f2ec1174b882c453e95b38f`
Not working version, nixpkgs hash: `H=7d38cab61f2f72c62d4a943c29662d62df44afcd`
```sh
nix eval "github:nixos/nixpkgs/$H#eza.version"
nix run "github:nixos/nixpkgs/$H#eza" -- -l some/path
```

---
The 0.15.3 is the version that introduced the `--color-scale` option, which I'm NOT using here.

**Comment by piechologist** [comment]
That has been fixed in 0.16.0. Per the release notes:

> We fixed the accidental breaking change with --color-scale suddenly requiring an argument introduced in v0.15.3, now it defaults to all.

You'd need `--color-scale=all` for 0.15.3.

**Comment by bew** [comment]
I'm NOT using `--color-scale`, and initially noticed this behavior on 0.16.0 actually
![image](https://github.com/eza-community/eza/assets/9730330/1d721497-9262-4642-809c-ee09a62cf11e)

**Comment by MartinFillon** [comment]
well it is indeed a bug and not linked to color-scaling

**Comment by piechologist** [comment]
This color scale feature is a bit confusing to me, too. I guess you want:
```shell
eza -l --color-scale=all --color-scale-mode=fixed  # 0.15.3
eza -l --color-scale-mode=fixed  # 0.16.0+
```
Unfortunately, the default is `--color-scale-mode=gradient` which ignores `EZA_COLORS` even when not using `--color-scale`.

**Comment by holmesrichards** [comment]
For me (using v0.16.0) `--color-scale-mode=fixed` still does not work for file ages:

![image](https://github.com/eza-community/eza/assets/56895621/80ece9ec-5543-479a-a8f4-eb11b94d3c87)

(For the above I am using `EXA_COLORS` but it still doesn't work if that is unset.)

**Comment by piechologist** [comment]
> For me (using v0.16.0) `--color-scale-mode=fixed` still does not work for file ages:

AFAIK, there's only a single `EZA_COLORS`'s `da` parameter we can define so, there's no fixed color scale for file ages at all. A bit confusing, really…

**Comment by holmesrichards** [comment]
Can confirm above bug in v0.16.0, Linux Mint 21.2: `uu` and `ur` work but `sn` and `sb` do not:

![image](https://github.com/eza-community/eza/assets/56895621/8f5e4cb1-c26c-4602-95cb-75bb5f374362)

**Comment by bew** [comment]
Helloo o/
Unfortunately I don't think the fix is correct, I lost the ability to configure the unit color, see for yourself:

![image](https://github.com/eza-community/eza/assets/9730330/e1528634-2b2f-40d2-a068-5ac6abdbd503)
```sh
# Should give blue size number, yellow size unit, blue username, yellow date
EZA_COLORS=nm=34:um=33:uu=34:da=33
truncate --size 123M test-file
```
And then run `eza -l test-file` (currently at 0.17.0), and I get the size number AND unit as blue, instead of the unit as yellow. 

Please re-open :pray:

**Comment by MartinFillon** [comment]
[colors](https://github.com/eza-community/eza/blob/main/man/eza_colors.5.md) please read this and retry um doesnt exist and nm is for M size unit

**Comment by bew** [comment]
Hmm they do exist:

https://github.com/eza-community/eza/blob/edcf392c78abd8abea76d4f59fb639ad134a0d8b/man/eza_colors.5.md?plain=1#L135-L136
https://github.com/eza-community/eza/blob/edcf392c78abd8abea76d4f59fb639ad134a0d8b/man/eza_colors.5.md?plain=1#L153-L154

**Comment by MartinFillon** [comment]
thats my bad guess ctrl-f didnt work

**Comment by bew** [comment]
@cafkafk (friendly ping) could you re-open? 🙏

**Comment by bew** [comment]
Hello! I opened #975 to fix this bug 😉
